[package]
name = "wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
rand = "0.8.5"
wasm-bindgen = "0.2.88"
getrandom = {version = "0.2.11", features = ["js"]}
serde = {version = "1.0.192", features = ["derive"]}
serde-wasm-bindgen = "0.6.1"